services:
  postgres:
    image: postgres:17.5-alpine3.21
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    ports:
      - 5432:5432/tcp
    volumes:
      - ./data/postgres:/var/lib/postgresql/data