[database]
url = "postgres://localhost:5432/main"
user = "admin"
password = "password"

[security]
secret = "my-awesome-jwt-secret-that-is-extremely-hidden"

[services]
github = { access-token = "" }

[serve]
endpoint = "localhost:3000"

